language: go

go:
  - "1.11.x"

env:
  - GO111MODULE=on

services:
  - postgresql

before_script:
  - psql -c 'create database goapp_test;' -U postgres
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: goapp

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get $(go list ./... | grep -v /vendor/)

script: buffalo test

after_success: 
  - curl -I -u BuildUser:11b8474a46b550321e144ae460066753bf "http://10.128.46.173:8080/job/go-web-app/build?token=SECURETOKEN"
