---
development:
  dialect: postgres
  database: goapp_development
  user: skorz
  password: 1q2w3e4r
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://skorz:1q2w3e4r@127.0.0.1:5432/goapp_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/goapp_production?sslmode=disable"}}
