version: '3'
services:   
  db:
    environment:
      - POSTGRES_USER=skorz
      - POSTGRES_PASSWORD=1q2w3e4r
      - POSTGRES_DB=goapp_development
    image: postgres
    ports:
      - 5432:5432
  go_application: 
    image: goapp:latest
    ports:
      - 3000:3000
    depends_on:
      - db
    links: 
      - db